### ISSUE TITLE
VS-0013 no se visualiza el botn de cerrar modal de producto

### ISSUE THREAD

**Issue by jccampos2007** [valeriacampos17/vale-shop#20]
no se visualiza el botn de cerrar modal de producto

![image](https://github.com/user-attachments/assets/0efe2194-a93b-448a-b72d-304e36a9bbf0)

**Comment by Angelottiasso** [comment]
ya se realizo esa tarea en una asignación anterior.

**Comment by Angelottiasso** [comment]
Ya se arreglo ese problema en la asignación anterior.
